# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adverts.SubCategory', verbose_name='\u041f\u043e\u0434 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
    ]
