# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0002_advert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0412\u043b\u0430\u0434\u0435\u043b\u0435\u0446'),
            preserve_default=False,
        ),
    ]
