# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_advert_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e \u0432'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 \u0430\u043a\u0442\u0438\u0432\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='advert',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e'),
        ),
        migrations.AddField(
            model_name='advert',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='\u0422\u043e\u0432\u0430\u0440 \u043f\u0440\u043e\u0434\u0430\u043d'),
        ),
        migrations.AddField(
            model_name='advert',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u0432'),
        ),
    ]
