# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20170119_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
    ]
