# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20170128_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='\u041b\u0443\u0447\u0448\u0435\u0435 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435 (\u043f\u0440\u0430\u0432\u044b\u0439 \u0431\u043b\u043e\u043a (\u043f\u0440\u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043e))'),
        ),
    ]
